/**
 * Dev helper: simulate a customer's inbound SMS by POSTing a correctly-signed Twilio
 * webhook to the running app, so you can test a full conversation locally without a real
 * phone or Twilio account. The agent replies asynchronously (the deterministic stub when
 * no ANTHROPIC_API_KEY is set), and the reply shows up in the console thread.
 *
 *   pnpm tsx scripts/simulate-inbound.ts
 *   pnpm tsx scripts/simulate-inbound.ts --from=+15550100001 --body="do you have this in navy?"
 *
 * Defaults to Maya Chen (+15550100001, seeded + opted-in) texting Demo Apparel Co
 * (+15555550100). Requires the dev server running and TWILIO_AUTH_TOKEN set in .env
 * (it's only used to forge the signature the webhook verifies — no real SMS is sent
 * while SEND_REAL_SMS=false).
 */
import crypto from "node:crypto";

import { config as loadDotenv } from "dotenv";

loadDotenv({ quiet: true });

const APP_URL = process.env.APP_URL ?? "http://localhost:3000";
const AUTH_TOKEN = process.env.TWILIO_AUTH_TOKEN;

if (!AUTH_TOKEN) {
  console.error(
    "TWILIO_AUTH_TOKEN must be set in .env — it's used only to sign the simulated webhook.",
  );
  process.exit(1);
}

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = a.match(/^--([^=]+)=(.*)$/);
    return m ? [m[1], m[2]] : [a.replace(/^--/, ""), "true"];
  }),
);

const from = (args.from as string) ?? "+15550100001"; // Maya Chen (seeded, opted-in)
const to = (args.to as string) ?? "+15555550100"; // Demo Apparel Co inbound number
const body =
  (args.body as string) ?? "Hi! Does the field jacket run true to size? I'm usually a medium.";

const url = `${APP_URL}/api/webhooks/twilio/inbound`;
const params: Record<string, string> = {
  From: from,
  To: to,
  Body: body,
  MessageSid: `SM${crypto.randomBytes(16).toString("hex")}`,
  AccountSid: process.env.TWILIO_ACCOUNT_SID ?? "ACdemo0000000000000000000000000000",
  NumMedia: "0",
};

// Twilio's scheme: base64( HMAC-SHA1( url + each sorted key concatenated with its raw
// value, keyed by the auth token ) ). Matches twilio.validateRequest on the server.
const data = Object.keys(params)
  .sort()
  .reduce((acc, k) => acc + k + params[k], url);
const signature = crypto
  .createHmac("sha1", AUTH_TOKEN)
  .update(Buffer.from(data, "utf-8"))
  .digest("base64");

async function main() {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "content-type": "application/x-www-form-urlencoded",
      "x-twilio-signature": signature,
    },
    body: new URLSearchParams(params).toString(),
  });

  console.log(`POST ${url} -> ${res.status} ${res.statusText}`);
  console.log("response:", await res.text());
  console.log(`\nSimulated ${from} → ${to}:\n  "${body}"`);
  if (res.ok) {
    console.log(
      "\nThe agent replies asynchronously. Open the console → Conversations → the matching\n" +
        "customer to watch the reply land (keyless: generated by the stub agent, 'sent' via mock).",
    );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
